import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="min-h-full flex flex-col">
  <nav
    style={{
      padding: "20px",
      borderBottom: "1px solid gray",
      display: "flex",
      gap: "20px",
    }}
  >
    <Link href="/dashboard">Dashboard</Link>

    <Link href="/resumes">Resumes</Link>

    <Link href="/profile">Profile</Link>
  </nav>

  {children}
</body> 
    </html>
  );
}
